Repository monkeyhurray/Change-Days, pull requests merged in 2024-03, with the labels that each got.

#1 Feat : 404페이지
  .github/image.png
  .github/pull_request_template.md
  src/app/not-found.tsx
Labels: 이거 봐주세요

#3 Signup Page 생성
  src/app/layout.tsx
  src/app/page.tsx
  src/app/sign/signup/page.tsx
Labels: Less important

#2 Feat : 검색 기능 추가, Add : test용 db추가
  db.json
  src/app/search/page.tsx
  src/types/index.ts
Labels: 이거 봐주세요

#4 [ADD] Mypage/database : supabase Setup
  package-lock.json
  package.json
  src/app/mypage/[id]/page.tsx
  src/app/mypage/page.tsx
  src/app/page.tsx
  src/supabase/supabase.ts
  src/types/supabase.ts
Labels: 이거 봐주세요

#6 Searchpage
  db.json
  package-lock.json
  package.json
  src/app/layout.tsx
  src/app/search/page.tsx
  src/app/test/page.tsx
  src/components/ChallengeCard.tsx
  src/components/TodoCard.tsx
  src/types/index.ts
Labels: 이거 봐주세요

#7 Mypage/database
  src/app/mypage/[id]/challenges/page.tsx
  src/app/mypage/[id]/page.tsx
  src/app/mypage/page.tsx
  src/components/supabase/ChallengeData.tsx
  src/components/supabase/UserData.tsx
  src/supabase/supabase.ts
  src/types/supabase.ts
Labels: 이거 봐주세요

#9 Sign/signup
  package-lock.json
  package.json
  src/app/layout.tsx
  src/app/not-found.tsx
  src/app/page.tsx
  src/app/provider.tsx
  src/app/sign/signup/page.tsx
  src/types/index.ts
  src/utils/supabaseClient.ts
Labels: 이거 봐주세요, 경과를 지켜봐야함

#10 Mypage/database
  package-lock.json
  src/app/mypage/[id]/challenges/create/page.tsx
  src/app/mypage/[id]/challenges/done/page.tsx
  src/app/mypage/[id]/challenges/ongoing/page.tsx
  src/app/mypage/[id]/challenges/page.tsx
  src/app/mypage/[id]/page.tsx
  src/app/page.tsx
  src/app/test/page.tsx
  src/supabase/supabase.ts
  src/types/index.ts
  src/utils/supabaseClient.ts
Labels: 이거 봐주세요

#11 [Sign/signin] 로그인 기능 구현 완료
  package-lock.json
  src/app/sign/signin/page.tsx
  src/app/sign/signup/page.tsx
Labels: 이거 봐주세요

#12 Main page
  public/mainImg.jpg
  src/app/challenge/[id]/page.tsx
  src/app/page.tsx
  src/components/common/CustomModal.tsx
  src/components/common/Footer.tsx
  src/components/common/Header.tsx
  src/components/common/MainSlider.tsx
  src/components/common/UploadModal.tsx
  tailwind.config.ts
Labels: 이거 봐주세요

#13 Searchpage
  .github/pull_request_template.md
  db.json
  src/app/search/page.tsx
  src/app/test/page.tsx
  src/components/ChallengeCard.tsx
  src/components/TodoCard.tsx
Labels: 이거 봐주세요, 경과를 지켜봐야함

#14 Mypage/database
  src/app/mypage/[id]/challenges/ongoing/page.tsx
  src/types/supabase.ts
Labels: Less important

#15 [MOD] mypages setting, type fixed
  .eslintrc.json
  package-lock.json
  src/app/mypage/[id]/challenges/page.tsx
  src/app/mypage/[id]/page.tsx
  src/app/sign/signin/page.tsx
  src/types/index.ts
  src/types/supabase.ts
Labels: 이거 봐주세요, 경과를 지켜봐야함

#16 Session: 로그인/비로그인 시, 사용자가 접근 가능한 페이지 지정 및 권한 부여
  src/app/mypage/[id]/layout.tsx
  src/app/sign/signin/page.tsx
  src/app/sign/signup/page.tsx
  src/components/common/Header.tsx
Labels: 이거 봐주세요, 경과를 지켜봐야함

#17 [MOD]mypage modal setting
  src/app/mypage/[id]/page.tsx
  src/app/mypage/[id]/profile/page.tsx
  src/components/mypage/UserData.tsx
Labels: Less important

#18 Profile/style
  src/app/mypage/[id]/challenges/create/page.tsx
  src/app/mypage/[id]/challenges/done/page.tsx
  src/app/mypage/[id]/challenges/ongoing/page.tsx
  src/app/mypage/challenges/page.tsx
  src/app/mypage/layout.tsx
  src/app/mypage/page.tsx
  src/app/mypage/profile/page.tsx
  src/app/sign/signup/page.tsx
Labels: Less important

#19 Searchpage
  src/app/search/page.tsx
  src/components/ChallengeCard.tsx
  src/components/searchPage/ChallengeCard.tsx
Labels: 부분적 완성, 이거 봐주세요, 경과를 지켜봐야함

#20 Uploadbtn
  .eslintrc.json
  db.json
  next.config.mjs
  package-lock.json
  package.json
  public/camera.jpg
  src/app/create-challenge/page.tsx
  src/components/common/Create-ChallengeBar.tsx
  src/components/createChallenge/createCalendar.ts
  src/components/hooks/useChallengeMutation.ts
Labels: 부분적 완성, 이거 봐주세요

#25 [ADD]mypage/challenges logic created
  src/app/mypage/challenges/page.tsx
Labels: 부분적 완성, 이거 봐주세요

#26 [ADD] created util fc (src/utils/timeutils.ts
  src/app/mypage/challenges/page.tsx
  src/utils/timeutils.ts
Labels: 이거 봐주세요

#27 fix : 참가하기 추가, 홈화면 search btn enter 쳤을 때 검색 페이지로 넘어가게 처리
  src/app/challenge/[id]/page.tsx
  src/app/mypage/profile/page.tsx
  src/components/challenge/ParticipateBtn.tsx
  src/components/common/Header.tsx
  src/components/common/MainSlider.tsx
  src/components/home/Search.tsx
Labels: 이거 봐주세요, Less important

#28 [FIX] data types setting done
  src/app/mypage/challenges/page.tsx
Labels: Less important

#29 Fix : 메인페이지검색-> 검색페이지 정상출력,
  src/app/search/page.tsx
  src/app/test/page.tsx
  src/components/searchPage/ChallengeCard.tsx
  src/utils/timeutils.ts
Labels: enhancement, 이거 봐주세요

#31 fix: 홈페이지 ssr로 변경
  src/app/page.tsx
  src/components/common/HomeChallenges.tsx
Labels: Less important

#33 Create challenge
  src/app/challenge/[id]/page.tsx
  src/app/create-challenge/page.tsx
  src/app/mypage/challenges/page.tsx
  src/app/mypage/layout.tsx
  src/app/mypage/profile/page.tsx
  src/components/createChallenge/createCalendar.ts
  src/components/hooks/useChallengeMutation.ts
Labels: 부분적 완성, 이거 봐주세요

#32 [MOD] add categori in challenges page
  src/app/mypage/challenges/page.tsx
  src/utils/timeutils.ts
Labels: Less important

#34 Challenge/data
  src/components/challenge/ParticipateBtn.tsx
  src/components/common/MainSlider.tsx
Labels: Less important

#36 Challenge/data
  src/app/challenge/[id]/page.tsx
Labels: Less important

#37 fix: img 경로 변경
  src/app/create-challenge/page.tsx
Labels: 이거 이미 있는 거임, 이거 봐주세요

#39 [MOD] frequency -> durationMessage
  src/app/challenge/[id]/page.tsx
Labels: Less important

#40 Create challenge
  src/app/create-challenge/page.tsx
  src/components/createChallenge/createCalendar.ts
Labels: 부분적 완성, 이거 봐주세요

#42 Fix: 값이 없으면 등록이 되지 않게 수정
  src/app/create-challenge/page.tsx
Labels: 부분적 완성, 이거 봐주세요

#43 Mypage/database
  src/app/challenge/[id]/page.tsx
  src/app/mypage/challenges/[id]/page.tsx
  src/app/mypage/challenges/page.tsx
  src/types/supabase.ts
  src/utils/fetchChallenges.ts
  src/utils/timeutils.ts
Labels: 버그발견

#44 Create challenge
  src/app/create-challenge/page.tsx
Labels: 버그발견, 부분적 완성

#46 Correct: import 오타 수정
  src/app/sign/signup/page.tsx
Labels: Less important

#47 dev 변경 사항 반영
  package-lock.json
  package.json
  src/app/layout.tsx
  src/app/mypage/layout.tsx
  src/app/provider.tsx
  src/app/sign/EyeFilledIcon.jsx
  src/app/sign/EyeSlashFilledIcon.jsx
  src/app/sign/signin/page.tsx
  src/app/sign/signup/page.tsx
  src/components/common/Header.tsx
  src/constants/errorCode.ts
  tailwind.config.ts
Labels: Less important

#48 Create challenge
  src/app/create-challenge/page.tsx
Labels: Less important

#49 [FIX] timeutil fixed
  src/app/challenge/[id]/page.tsx
  src/app/mypage/challenges/page.tsx
  src/components/common/MainSlider.tsx
  src/types/supabase.ts
Labels: 이거 봐주세요, 버그 해결

#51 Mypage/database
  src/app/challenge/[id]/page.tsx
  src/app/mypage/challenges/[id]/page.tsx
  src/app/mypage/challenges/page.tsx
Labels: 부분적 완성, 이거 봐주세요

#53 Feat: 마이 페이지, 상세 페이지의 닉네임 수정 및 기본 이미지 등록 등 안 되는 기능 모두 코드 추가 혹은 수정하여 구현
  public/bonobo.jpeg
  src/app/challenge/[id]/page.tsx
  src/app/mypage/challenges/[id]/page.tsx
  src/app/mypage/challenges/page.tsx
  src/app/mypage/page.tsx
  src/app/mypage/profile/page.tsx
  src/app/sign/signup/page.tsx
  src/components/challenge/ParticipateBtn.tsx
  src/components/common/HomeChallenges.tsx
  src/components/common/MainSlider.tsx
  src/components/mypage/UserData.tsx
Labels: 이거 봐주세요

#55 Fix : 필요없는 코드 삭제
  src/app/mypage/profile/page.tsx
  src/components/searchPage/ChallengeCard.tsx
Labels: Less important

#56 Create challenge
  src/app/mypage/page.tsx
  src/app/mypage/profile/page.tsx
  src/components/mypage/UserData.tsx
Labels: 버그 해결

#57 Feat: 회원가입 페이지 - 유효성 검사 양식에 맞지 않게 제출 시, 반환 처리
  src/app/sign/signup/page.tsx
Labels: Less important
